const metrics = [
  {
    metric_type: "http",
    name: "test1",
    execution_id: "b492d56c-822b-4025-90ec-43d5c9933e31",
    location: "api",
    org_id: "org_2ksPhfdRnRSAV7VAe7giFkoGB7U",
    pulse_id: "5d7b70c8-7b86-11ef-8eb0-56c37528c92d",
    run_id: "f621593f-40e2-46c6-82d4-05895eb5ff84",
    request_timestamp: 1727300249607,
    resolved_ip_addresses: ["141.148.20.193"],
    dns_lookup_time: 0.000696916,
    tcp_connection_time: 0.255490916,
    tls_handshake_time: 1.973184833,
    time_to_first_byte: 0.1862995,
    total_duration: 2.417554333,
    content_download_time: 0.001,
    request_headers: {
      Accept: ["application/json"],
      "Content-Type": ["application/json"],
      Cookie: ["session_id=12345"],
    },
    response_headers: {
      Connection: ["keep-alive"],
      "Content-Length": ["17"],
      "Content-Type": ["application/json"],
      Date: ["Wed, 25 Sep 2024 21:37:31 GMT"],
      "Strict-Transport-Security": ["max-age=31536000; includeSubDomains"],
    },
    status_code: 200,
    error: "",
    ssl_metrics: null,
    dns_metrics: null,
    mtr_metrics: null,
    origin_geo_data: {
      ip: "189.16.81.54",
      country: {
        name: "Brazil",
        iso_code: "BR",
      },
      city: {
        name: "São Paulo",
      },
      location: {
        latitude: -23.6283,
        longitude: -46.6409,
        time_zone: "America/Sao_Paulo",
        accuracy_radius: 500,
      },
      isp: {
        isp: "Embratel",
        organization: "Embratel",
        asn: 4230,
        as_organization: "CLARO S.A.",
      },
    },
    destination_geo_data: {
      ip: "141.148.20.193",
      country: {
        name: "United States",
        iso_code: "US",
      },
      city: {
        name: "Ashburn",
      },
      location: {
        latitude: 39.018,
        longitude: -77.539,
        time_zone: "America/New_York",
        accuracy_radius: 20,
      },
      isp: {
        isp: "Oracle Cloud",
        organization: "Oracle Cloud",
        asn: 31898,
        as_organization: "ORACLE-BMC-31898",
      },
    },
    response_size: 17,
    response_data: {
      working: true,
    },
    redirect_duration: 0,
    redirect_chain_length: 0,
    http_version: "HTTP/1.1",
    tls_protocol_version: "TLS 3.4",
    browser_metrics_duration: 0,
    browser_metrics: null,
    evaluation_function_return: {
      failureReasons: [
        "isSslValid is false",
        "isStatusOk is false",
        "isDnsFast is false",
      ],
      name: "ali",
      success: false,
      variableStates: {
        isDnsFast: false,
        isSslValid: false,
        isStatusOk: false,
        metric: {},
        success: false,
      },
    },
  },
  {
    metric_type: "http",
    name: "test2",
    execution_id: "988416fa-88bf-4955-aa04-c950a682a65e",
    location: "api",
    org_id: "org_2ksPhfdRnRSAV7VAe7giFkoGB7U",
    pulse_id: "5d7b70c8-7b86-11ef-8eb0-56c37528c92d",
    run_id: "f621593f-40e2-46c6-82d4-05895eb5ff84",
    request_timestamp: 1727300252028,
    resolved_ip_addresses: ["142.251.135.100", "2800:3f0:4004:808::2004"],
    dns_lookup_time: 0.002152417,
    tcp_connection_time: 0.130011541,
    tls_handshake_time: 0.1181125,
    time_to_first_byte: 0.495982041,
    total_duration: 0.837026875,
    content_download_time: 0.086390625,
    request_headers: {
      Accept: ["application/json"],
      "Content-Type": ["application/json"],
      Cookie: ["session_id=12345"],
    },
    response_headers: {
      "Accept-Ch": ["Sec-CH-Prefers-Color-Scheme"],
      "Alt-Svc": ['h3=":443"; ma=2592000,h3-29=":443"; ma=2592000'],
      "Cache-Control": ["private, max-age=0"],
      "Content-Security-Policy-Report-Only": [
        "object-src 'none';base-uri 'self';script-src 'nonce-WArgeMBOLYhyvGzQZAykaQ' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp",
      ],
      "Content-Type": ["text/html; charset=ISO-8859-1"],
      Date: ["Wed, 25 Sep 2024 21:37:48 GMT"],
      Expires: ["-1"],
      P3p: ['CP="This is not a P3P policy! See g.co/p3phelp for more info."'],
      Server: ["gws"],
      "Set-Cookie": [
        "session_id=; expires=Mon, 01-Jan-1990 00:00:00 GMT; path=/; domain=www.google.com",
        "session_id=; expires=Mon, 01-Jan-1990 00:00:00 GMT; path=/; domain=.www.google.com",
        "session_id=; expires=Mon, 01-Jan-1990 00:00:00 GMT; path=/; domain=google.com",
        "session_id=; expires=Mon, 01-Jan-1990 00:00:00 GMT; path=/; domain=.google.com",
        "AEC=AVYB7cpWBTJHhOxfmtUkO_92GKaRmeAWnhqhtMamzNxl6YdhTxYlKi6cZA; expires=Mon, 24-Mar-2025 21:37:48 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax",
        "NID=517=TSBVvPm8KG7egFJUGoh3ywqRFSF3yHZGPVAzOqG4Kn87m-jYrrGaN9qAFTSsINW-YtKypKMbklJwe6bJuwkyQMIiIKI-PyFe1f88idl-4HmAXn66JMJwBG6GSVJhmiIHu57XrwqayJNnQvqbCSYmh53x-rvRrl92KvTdOsWPL8gyHlVfyLPTFh37wP1-tGc13-s; expires=Thu, 27-Mar-2025 21:37:48 GMT; path=/; domain=.google.com; HttpOnly",
      ],
      "X-Frame-Options": ["SAMEORIGIN"],
      "X-Xss-Protection": ["0"],
    },
    status_code: 200,
    error: "",
    ssl_metrics: {
      request_timestamp: 1727300252029,
      resolved_ips: ["142.251.135.100", "2800:3f0:4004:808::2004"],
      handshake_duration: 3.34e-7,
      connection_duration: 0.167700958,
      common_name: "www.google.com",
      alternative_names: ["www.google.com"],
      issuer_common_name: "WR2",
      issuer_country: "US",
      issuer_organization: "Google Trust Services",
      cert_fingerprint_sha1: "",
      cert_fingerprint_sha256:
        "f3249c292540a8f2f302121cb78df57597a17f9009bedd648e3befd2889fdaed",
      not_valid_before: 1724656549000000000,
      not_valid_after: 1731914148000000000,
      cipher_suite: "TLS_AES_128_GCM_SHA256",
      protocol_version: "TLSv1.3",
      dns_lookup_time: 0.149799333,
      days_until_expiry: 53,
      total_duration: 0.900528792,
      ocsp_response_status: "Good",
      crl_check_status: "CRL not available",
      certificate_chain_length: 3,
      root_ca_common_name: "",
      key_exchange_algorithm: "ECDHE",
      server_key_length: 256,
      public_key_algorithm: "ECDSA",
      signature_algorithm: "SHA256-RSA",
      session_resumption_supported: false,
      hsts_status: false,
      visual_chain: {
        entries: [
          {
            order: 1,
            name: "www.google.com",
            type: "Leaf",
            issuer: "Google Trust Services",
          },
          {
            order: 2,
            name: "WR2",
            type: "Intermediate",
            issuer: "Google Trust Services LLC",
          },
          {
            order: 3,
            name: "GTS Root R1",
            type: "Root",
            issuer: "GlobalSign nv-sa",
          },
        ],
      },
      security_score: {
        total_score: 81,
        max_score: 100,
        components: [
          {
            name: "Protocol Version",
            score: 20,
            max_score: 20,
            reason: "Using the latest TLS version (1.3)",
          },
          {
            name: "Cipher Suite",
            score: 15,
            max_score: 15,
            reason: "Using strong TLS 1.3 cipher suite",
          },
          {
            name: "Certificate Validity",
            score: 8,
            max_score: 10,
            reason: "Certificate valid for more than a month",
          },
          {
            name: "Key Exchange Strength",
            score: 15,
            max_score: 15,
            reason:
              "Using strong ECDHE key exchange with key length >= 256 bits",
          },
          {
            name: "Signature Algorithm",
            score: 10,
            max_score: 10,
            reason: "Using strong signature algorithm",
          },
          {
            name: "OCSP Stapling",
            score: 3,
            max_score: 5,
            reason: "OCSP available but not stapled",
          },
          {
            name: "HSTS",
            score: 0,
            max_score: 5,
            reason: "HSTS not enabled",
          },
          {
            name: "Certificate Chain Length",
            score: 5,
            max_score: 5,
            reason: "Optimal certificate chain length: 3",
          },
          {
            name: "Session Resumption",
            score: 0,
            max_score: 5,
            reason: "Session resumption not supported",
          },
          {
            name: "Public Key Algorithm",
            score: 5,
            max_score: 5,
            reason: "Using ECDSA with key length 256 bits",
          },
        ],
      },
    },
    dns_metrics: {
      request_timestamp: 1727300252029,
      resolved_ips: ["142.251.129.228", "2800:3f0:4001:836::2004"],
      total_duration: 1.244070542,
      dns_lookup_time: 0.842160126,
      network_latency: 0.121917042,
      dnssec_validation_time: 0.202508417,
      client_processing_time: 0.07748495700000002,
      dns_server_used: "8.8.8.8:53",
      dnssec_status: "unsigned",
      errors: null,
      response_size: 328,
      rcode: 0,
      edns_used: false,
      edns_version: 0,
      udp_supported: true,
      tcp_supported: true,
      dnskey_present: false,
      ds_present: false,
      a_records: ["142.251.129.228"],
      aaaa_records: ["2800:3f0:4001:836::2004"],
      cname_records: null,
      mx_records: null,
      ns_records: null,
      soa_record: {
        primary_ns: "",
        admin_email: "",
        serial: 0,
        refresh: 0,
        retry: 0,
        expire: 0,
        minimum_ttl: 0,
      },
      txt_records: null,
      caa_records: null,
      reverse_dns_lookups: [
        {
          ip: "142.251.129.228",
          domain: "gru14s34-in-f4.1e100.net.",
          ttl: 1704,
          records: [
            "228.129.251.142.in-addr.arpa.\t1704\tIN\tPTR\tgru14s34-in-f4.1e100.net.",
          ],
        },
      ],
      nameservers_used: null,
      truncated: false,
      recursion_desired: false,
      recursion_available: false,
      authentic_data: false,
      checking_disabled: false,
    },
    mtr_metrics: {
      request_timestamp: 1727300252029,
      target: "www.google.com",
      report_cycles: 10,
      max_hops: 13,
      packet_size: 64,
      src: "Mauros-MacBook-Pro-2.local",
      dst: "www.google.com",
      tos: 0,
      tests: 10,
      psize: 64,
      bit_pattern: "0x00",
      hubs: [
        {
          count: 1,
          host: "10.139.0.11",
          "Loss%": 0,
          Snt: 10,
          Last: 0.004413,
          Avg: 0.040852,
          Best: 0.0039889999999999995,
          Wrst: 0.093592,
          StDev: 0.037443,
          HostNames: null,
          HostIPs: ["10.139.0.11"],
          IsDuplicate: false,
          IsDataMissing: false,
          WasUnreachableHop: false,
        },
        {
          count: 2,
          host: "192.168.122.202",
          "Loss%": 70,
          Snt: 10,
          Last: 0.09648699999999999,
          Avg: 0.07919499999999999,
          Best: 0.045158000000000004,
          Wrst: 0.09648699999999999,
          StDev: 0.029478,
          HostNames: null,
          HostIPs: ["192.168.122.202"],
          IsDuplicate: false,
          IsDataMissing: false,
          WasUnreachableHop: false,
        },
        {
          count: 3,
          host: "189.16.81.49",
          "Loss%": 30,
          Snt: 10,
          Last: 0.036979,
          Avg: 0.037381,
          Best: 0.031966,
          Wrst: 0.04859599999999999,
          StDev: 0.005694,
          HostNames: null,
          HostIPs: ["189.16.81.49"],
          IsDuplicate: false,
          IsDataMissing: false,
          WasUnreachableHop: false,
          geo_data: {
            ip: "189.16.81.49",
            country: {
              name: "Brazil",
              iso_code: "BR",
            },
            city: {
              name: "São Paulo",
            },
            location: {
              latitude: -23.6283,
              longitude: -46.6409,
              time_zone: "America/Sao_Paulo",
              accuracy_radius: 500,
            },
            isp: {
              isp: "Embratel",
              organization: "Embratel",
              asn: 4230,
              as_organization: "CLARO S.A.",
            },
          },
        },
        {
          count: 4,
          host: "embratel-t0-6-0-1-0-15003-agg02.spoph.embratel.net.br (200.178.127.9)",
          "Loss%": 10,
          Snt: 10,
          Last: 0.03594,
          Avg: 0.06369,
          Best: 0.032103,
          Wrst: 0.13058,
          StDev: 0.041909999999999996,
          HostNames: ["embratel-t0-6-0-1-0-15003-agg02.spoph.embratel.net.br"],
          HostIPs: ["200.178.127.9"],
          IsDuplicate: false,
          IsDataMissing: false,
          WasUnreachableHop: false,
          geo_data: {
            ip: "200.178.127.9",
            country: {
              name: "Brazil",
              iso_code: "BR",
            },
            city: {
              name: "Ananindeua",
            },
            location: {
              latitude: -1.3646,
              longitude: -48.3724,
              time_zone: "America/Belem",
              accuracy_radius: 20,
            },
            isp: {
              isp: "Embratel",
              organization: "Embratel",
              asn: 4230,
              as_organization: "CLARO S.A.",
            },
          },
        },
        {
          count: 5,
          host: "ebt-b1104-tcore01.spolp.embratel.net.br (200.230.131.7)",
          "Loss%": 0,
          Snt: 10,
          Last: 0.05074,
          Avg: 0.082155,
          Best: 0.043683,
          Wrst: 0.13359000000000001,
          StDev: 0.038066,
          HostNames: ["ebt-b1104-tcore01.spolp.embratel.net.br"],
          HostIPs: ["200.230.131.7"],
          IsDuplicate: false,
          IsDataMissing: false,
          WasUnreachableHop: false,
          geo_data: {
            ip: "200.230.131.7",
            country: {
              name: "Brazil",
              iso_code: "BR",
            },
            city: {
              name: "",
            },
            location: {
              latitude: -22.8305,
              longitude: -43.2192,
              time_zone: "America/Sao_Paulo",
              accuracy_radius: 1000,
            },
            isp: {
              isp: "Embratel",
              organization: "Embratel",
              asn: 4230,
              as_organization: "CLARO S.A.",
            },
          },
        },
        {
          count: 6,
          host: "ebt-b11-tcore01.spoph.embratel.net.br (200.230.0.6)",
          "Loss%": 20,
          Snt: 10,
          Last: 0.13329,
          Avg: 0.074208,
          Best: 0.046762,
          Wrst: 0.13329,
          StDev: 0.031933,
          HostNames: ["ebt-b11-tcore01.spoph.embratel.net.br"],
          HostIPs: ["200.230.0.6"],
          IsDuplicate: false,
          IsDataMissing: false,
          WasUnreachableHop: false,
          geo_data: {
            ip: "200.230.0.6",
            country: {
              name: "Brazil",
              iso_code: "BR",
            },
            city: {
              name: "",
            },
            location: {
              latitude: -22.8305,
              longitude: -43.2192,
              time_zone: "America/Sao_Paulo",
              accuracy_radius: 1000,
            },
            isp: {
              isp: "Embratel",
              organization: "Embratel",
              asn: 4230,
              as_organization: "CLARO S.A.",
            },
          },
        },
        {
          count: 7,
          host: "ebt-b12-core01.spo.embratel.net.br (200.230.158.30)",
          "Loss%": 30,
          Snt: 10,
          Last: 0.046062,
          Avg: 0.094905,
          Best: 0.041331,
          Wrst: 0.13197,
          StDev: 0.039356,
          HostNames: ["ebt-b12-core01.spo.embratel.net.br"],
          HostIPs: ["200.230.158.30"],
          IsDuplicate: false,
          IsDataMissing: false,
          WasUnreachableHop: false,
          geo_data: {
            ip: "200.230.158.30",
            country: {
              name: "Brazil",
              iso_code: "BR",
            },
            city: {
              name: "",
            },
            location: {
              latitude: -22.8305,
              longitude: -43.2192,
              time_zone: "America/Sao_Paulo",
              accuracy_radius: 1000,
            },
            isp: {
              isp: "Embratel",
              organization: "Embratel",
              asn: 4230,
              as_organization: "CLARO S.A.",
            },
          },
        },
        {
          count: 8,
          host: "ebt-b1101-core01.rjo.embratel.net.br (200.230.251.1)",
          "Loss%": 20,
          Snt: 10,
          Last: 0.12432,
          Avg: 0.080818,
          Best: 0.046655,
          Wrst: 0.12432,
          StDev: 0.028053,
          HostNames: ["ebt-b1101-core01.rjo.embratel.net.br"],
          HostIPs: ["200.230.251.1"],
          IsDuplicate: false,
          IsDataMissing: false,
          WasUnreachableHop: false,
          geo_data: {
            ip: "200.230.251.1",
            country: {
              name: "Brazil",
              iso_code: "BR",
            },
            city: {
              name: "",
            },
            location: {
              latitude: -22.8305,
              longitude: -43.2192,
              time_zone: "America/Sao_Paulo",
              accuracy_radius: 1000,
            },
            isp: {
              isp: "Embratel",
              organization: "Embratel",
              asn: 4230,
              as_organization: "CLARO S.A.",
            },
          },
        },
        {
          count: 9,
          host: "ebt-b211-agg03.rjo.embratel.net.br (200.244.18.8)",
          "Loss%": 20,
          Snt: 10,
          Last: 0.10064000000000001,
          Avg: 0.07667600000000001,
          Best: 0.041603,
          Wrst: 0.13091999999999998,
          StDev: 0.033582,
          HostNames: ["ebt-b211-agg03.rjo.embratel.net.br"],
          HostIPs: ["200.244.18.8"],
          IsDuplicate: false,
          IsDataMissing: false,
          WasUnreachableHop: false,
          geo_data: {
            ip: "200.244.18.8",
            country: {
              name: "Brazil",
              iso_code: "BR",
            },
            city: {
              name: "",
            },
            location: {
              latitude: -22.8305,
              longitude: -43.2192,
              time_zone: "America/Sao_Paulo",
              accuracy_radius: 1000,
            },
            isp: {
              isp: "Embratel",
              organization: "Embratel",
              asn: 4230,
              as_organization: "CLARO S.A.",
            },
          },
        },
        {
          count: 10,
          host: "peer-b54-agg03.rjo.embratel.net.br (201.39.52.58)",
          "Loss%": 10,
          Snt: 10,
          Last: 0.046590000000000006,
          Avg: 0.05697,
          Best: 0.041894,
          Wrst: 0.14447,
          StDev: 0.032885,
          HostNames: ["peer-b54-agg03.rjo.embratel.net.br"],
          HostIPs: ["201.39.52.58"],
          IsDuplicate: false,
          IsDataMissing: false,
          WasUnreachableHop: false,
          geo_data: {
            ip: "201.39.52.58",
            country: {
              name: "Brazil",
              iso_code: "BR",
            },
            city: {
              name: "São Luís",
            },
            location: {
              latitude: -2.6495,
              longitude: -44.3044,
              time_zone: "America/Fortaleza",
              accuracy_radius: 500,
            },
            isp: {
              isp: "Embratel",
              organization: "Embratel",
              asn: 4230,
              as_organization: "CLARO S.A.",
            },
          },
        },
        {
          count: 11,
          host: "142.250.213.133",
          "Loss%": 50,
          Snt: 10,
          Last: 0.044374000000000004,
          Avg: 0.078377,
          Best: 0.043105,
          Wrst: 0.13076,
          StDev: 0.046696,
          HostNames: null,
          HostIPs: ["142.250.213.133"],
          IsDuplicate: false,
          IsDataMissing: false,
          WasUnreachableHop: false,
          geo_data: {
            ip: "142.250.213.133",
            country: {
              name: "United States",
              iso_code: "US",
            },
            city: {
              name: "",
            },
            location: {
              latitude: 37.751,
              longitude: -97.822,
              time_zone: "America/Chicago",
              accuracy_radius: 1000,
            },
            isp: {
              isp: "Google",
              organization: "Google",
              asn: 15169,
              as_organization: "GOOGLE",
            },
          },
        },
        {
          count: 12,
          host: "216.239.42.207",
          "Loss%": 20,
          Snt: 10,
          Last: 0.045343,
          Avg: 0.095619,
          Best: 0.045343,
          Wrst: 0.12909,
          StDev: 0.030928,
          HostNames: null,
          HostIPs: ["216.239.42.207"],
          IsDuplicate: false,
          IsDataMissing: false,
          WasUnreachableHop: false,
          geo_data: {
            ip: "216.239.42.207",
            country: {
              name: "United States",
              iso_code: "US",
            },
            city: {
              name: "",
            },
            location: {
              latitude: 37.751,
              longitude: -97.822,
              time_zone: "America/Chicago",
              accuracy_radius: 1000,
            },
            isp: {
              isp: "Google",
              organization: "Google",
              asn: 15169,
              as_organization: "GOOGLE",
            },
          },
        },
        {
          count: 13,
          host: "rio09s08-in-f4.1e100.net (142.251.135.100)",
          "Loss%": 10,
          Snt: 10,
          Last: 0.086684,
          Avg: 0.073384,
          Best: 0.044147,
          Wrst: 0.11807,
          StDev: 0.02832,
          HostNames: ["rio09s08-in-f4.1e100.net"],
          HostIPs: ["142.251.135.100"],
          IsDuplicate: false,
          IsDataMissing: false,
          WasUnreachableHop: false,
          geo_data: {
            ip: "142.251.135.100",
            country: {
              name: "United States",
              iso_code: "US",
            },
            city: {
              name: "Farmingdale",
            },
            location: {
              latitude: 40.7306,
              longitude: -73.4313,
              time_zone: "America/New_York",
              accuracy_radius: 1000,
            },
            isp: {
              isp: "Google Servers",
              organization: "Google Servers",
              asn: 15169,
              as_organization: "GOOGLE",
            },
          },
        },
      ],
      summary: {
        total_hops: 13,
        average_loss_percent: 22.307692307692307,
        average_latency_ms: 0.07186384615384615,
        average_jitter_ms: 0.021032833333333334,
        high_loss_hops: [2, 3, 4, 6, 7, 8, 9, 10, 11, 12, 13],
        high_latency_hops: null,
        high_jitter_hops: null,
        high_stdev_hops: null,
        slowest_hop: 12,
        slowest_hop_latency_ms: 0.095619,
        total_packet_loss: false,
        problematic_hops: [2, 3, 4, 6, 7, 8, 9, 10, 11, 12, 13],
        duplicate_ip_hops: null,
        multiple_ip_hops: null,
        data_missing_hops: null,
        recommendations: [
          "High packet loss detected at hops: [2 3 4 6 7 8 9 10 11 12 13]. Packet loss greater than 2% can cause network performance issues. Investigate network devices or routes at these hops.",
        ],
        unreachable_hop_count: 0,
      },
    },
    origin_geo_data: {
      ip: "189.16.81.54",
      country: {
        name: "Brazil",
        iso_code: "BR",
      },
      city: {
        name: "São Paulo",
      },
      location: {
        latitude: -23.6283,
        longitude: -46.6409,
        time_zone: "America/Sao_Paulo",
        accuracy_radius: 500,
      },
      isp: {
        isp: "Embratel",
        organization: "Embratel",
        asn: 4230,
        as_organization: "CLARO S.A.",
      },
    },
    destination_geo_data: {
      ip: "142.251.135.100",
      country: {
        name: "United States",
        iso_code: "US",
      },
      city: {
        name: "Farmingdale",
      },
      location: {
        latitude: 40.7306,
        longitude: -73.4313,
        time_zone: "America/New_York",
        accuracy_radius: 1000,
      },
      isp: {
        isp: "Google Servers",
        organization: "Google Servers",
        asn: 15169,
        as_organization: "GOOGLE",
      },
    },
    response_size: 23038,
    response_data:
      '<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="pt-BR"><head><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><meta content="/logos/doodles/2024/celebrating-popcorn-6753651837110076.2-l.png" itemprop="image"><meta content="Celebrando a pipoca" property="twitter:title"><meta content="Celebrando a Pipoca! #GoogleDoodle" property="twitter:description"><meta content="Celebrando a Pipoca! #GoogleDoodle" property="og:description"><meta content="summary_large_image" property="twitter:card"><meta content="@GoogleDoodles" property="twitter:site"><meta content="https://www.google.com/logos/doodles/2024/celebrating-popcorn-6753651837110076.3-2xa.gif" property="twitter:image"><meta content="https://www.google.com/logos/doodles/2024/celebrating-popcorn-6753651837110076.3-2xa.gif" property="og:image"><meta content="889" property="og:image:width"><meta content="400" property="og:image:height"><meta content="https://www.google.com/logos/doodles/2024/celebrating-popcorn-6753651837110076.3-2xa.gif" property="og:url"><meta content="video.other" property="og:type"><title>Google</title><script nonce="WArgeMBOLYhyvGzQZAykaQ">(function(){var _g={kEI:\'rIL0ZprXLKXH4-EP-_-E8Ak\',kEXPI:\'0,2504567,1195675,1139,3,538661,2872,2891,8349,34679,30022,196361,23366,6699,41949,68695,15676,8155,23350,6431,2,16003,9779,5864,6550,50243,6050,70159,15816,1804,34993,12089,342,1291,29278,21780,5208512,6218,3248,999,137,9,2,57,5991227,2841102,263,439,3,6,78,4,2,1,102,8,3,23936414,4043710,16673,43886,3,1603,3,2124363,23029351,6869,5930,19298,58718,22465,11647,7661,3315,15164,8182,49429,21669,6755,155,2484,21239,9140,4599,328,3217,4,1238,1766,12894,7707,4858,5,856,1670,5634,686,7291,505,3,7,2827,181,13257,5030,754,682,282,377,5407,8246,55,356,1856,2,9,746,4,4020,3749,757,4135,2378,1482,980,529,9151,3288,12095,473,797,377,2464,2943,2434,4,461,2,2639,197,187,2,940,2421,1070,729,7114,3554,1842,1708,2,442,149,289,3,605,3634,3094,771,251,2399,300,615,118,280,861,2,395,758,2,1015,23,1498,3275,246,183,2398,4,372,110,581,4,3,1451,41,228,1685,6,3,1191,1470,957,55,26,409,1097,692,211,232,4,250,221,3145,418,6,10,712,5,129,77,444,2,85,69,1,1554,201,194,1,505,1244,312,680,39,377,185,47,145,721,603,211,160,415,344,1954,203,5,547,62,22,52,17,152,317,145,948,41,444,1,3,370,517,2,145,812,162,61,43,480,1015,4,1,6,104,1551,131,419,319,701,2086,21,292,276,167,244,747,123,493,505,120,297,107,189,208,44,57,482,223,132,32,4,2198,275,5,224,100,102,366,126,250,484,175,133,74,42,657,57,1186,3,27,865,18,4,502,288,2,470,900,270,522,139,329,399,437,5,437,1371,3,7,58,3,21446701,3,1423,3,14475,3,16997,18,150,1854,1258,1088,7510268\',kBL:\'n3ES\',kOPI:89978449};(function(){var a;((a=window.google)==null?0:a.stvsc)?google.kEI=_g.kEI:window.google=_g;}).call(this);})();(function(){google.sn=\'webhp\';google.kHL=\'pt-BR\';})();(function(){\nvar h=this||self;function l(){return window.google!==void 0&&window.google.kOPI!==void 0&&window.google.kOPI!==0?window.google.kOPI:null};var m,n=[];function p(a){for(var b;a&&(!a.getAttribute||!(b=a.getAttribute("eid")));)a=a.parentNode;return b||m}function q(a){for(var b=null;a&&(!a.getAttribute||!(b=a.getAttribute("leid")));)a=a.parentNode;return b}function r(a){/^http:/i.test(a)&&window.location.protocol==="https:"&&(google.ml&&google.ml(Error("a"),!1,{src:a,glmm:1}),a="");return a}\nfunction t(a,b,c,d,k){var e="";b.search("&ei=")===-1&&(e="&ei="+p(d),b.search("&lei=")===-1&&(d=q(d))&&(e+="&lei="+d));d="";var g=b.search("&cshid=")===-1&&a!=="slh",f=[];f.push(["zx",Date.now().toString()]);h._cshid&&g&&f.push(["cshid",h._cshid]);c=c();c!=null&&f.push(["opi",c.toString()]);for(c=0;c<f.length;c++){if(c===0||c>0)d+="&";d+=f[c][0]+"="+f[c][1]}return"/"+(k||"gen_204")+"?atyp=i&ct="+String(a)+"&cad="+(b+e+d)};m=google.kEI;google.getEI=p;google.getLEI=q;google.ml=function(){return null};google.log=function(a,b,c,d,k,e){e=e===void 0?l:e;c||(c=t(a,b,e,d,k));if(c=r(c)){a=new Image;var g=n.length;n[g]=a;a.onerror=a.onload=a.onabort=function(){delete n[g]};a.src=c}};google.logUrl=function(a,b){b=b===void 0?l:b;return t("",a,b)};}).call(this);(function(){google.y={};google.sy=[];var d;(d=google).x||(d.x=function(a,b){if(a)var c=a.id;else{do c=Math.random();while(google.y[c])}google.y[c]=[a,b];return!1});var e;(e=google).sx||(e.sx=function(a){google.sy.push(a)});google.lm=[];var f;(f=google).plm||(f.plm=function(a){google.lm.push.apply(google.lm,a)});google.lq=[];var g;(g=google).load||(g.load=function(a,b,c){google.lq.push([[a],b,c])});var h;(h=google).loadAll||(h.loadAll=function(a,b){google.lq.push([a,b])});google.bx=!1;var k;(k=google).lx||(k.lx=function(){});var l=[],m;(m=google).fce||(m.fce=function(a,b,c,n){l.push([a,b,c,n])});google.qce=l;}).call(this);google.f={};(function(){\ndocument.documentElement.addEventListener("submit",function(b){var a;if(a=b.target){var c=a.getAttribute("data-submitfalse");a=c==="1"||c==="q"&&!a.elements.q.value?!0:!1}else a=!1;a&&(b.preventDefault(),b.stopPropagation())},!0);document.documentElement.addEventListener("click",function(b){var a;a:{for(a=b.target;a&&a!==document.documentElement;a=a.parentElement)if(a.tagName==="A"){a=a.getAttribute("data-nohref")==="1";break a}a=!1}a&&b.preventDefault()},!0);}).call(this);</script><style>#gbar,#guser{font-size:13px;padding-top:1px !important;}#gbar{height:22px}#guser{padding-bottom:7px !important;text-align:right}.gbh,.gbd{border-top:1px solid #c9d7f1;font-size:1px}.gbh{height:0;position:absolute;top:24px;width:100%}@media all{.gb1{height:22px;margin-right:.5em;vertical-align:top}#gbar{float:left}}a.gb1,a.gb4{text-decoration:underline !important}a.gb1,a.gb4{color:#00c !important}.gbi .gb4{color:#dd8e27 !important}.gbf .gb4{color:#900 !important}\n</style><style>body,td,a,p,.h{font-family:arial,sans-serif}body{margin:0;overflow-y:scroll}#gog{padding:3px 8px 0}td{line-height:.8em}.gac_m td{line-height:17px}form{margin-bottom:20px}.h{color:#1967d2}em{font-weight:bold;font-style:normal}.lst{height:25px;width:496px}.gsfi,.lst{font:18px arial,sans-serif}.gsfs{font:17px arial,sans-serif}.ds{display:inline-box;display:inline-block;margin:3px 0 4px;margin-left:4px}input{font-family:inherit}body{background:#fff;color:#000}a{color:#681da8;text-decoration:none}a:hover,a:active{text-decoration:underline}.fl a{color:#1967d2}a:visited{color:#681da8}.sblc{padding-top:5px}.sblc a{display:block;margin:2px 0;margin-left:13px;font-size:11px}.lsbb{background:#f8f9fa;border:solid 1px;border-color:#dadce0 #70757a #70757a #dadce0;height:30px}.lsbb{display:block}#WqQANb a{display:inline-block;margin:0 12px}.lsb{background:url(/images/nav_logo229.png) 0 -261px repeat-x;color:#000;border:none;cursor:pointer;height:30px;margin:0;outline:0;font:15px arial,sans-serif;vertical-align:top}.lsb:active{background:#dadce0}.lst:focus{outline:none}.Ucigb{width:458px}</style><script nonce="WArgeMBOLYhyvGzQZAykaQ">(function(){window.google.erd={jsr:1,bv:2085,de:true,dpf:\'vd8AvQlefXeuLSeFK0XGBNVzaXow_5XaGzGk7MGTjtU\'};\nvar g=this||self;var k,l=(k=g.mei)!=null?k:1,n,p=(n=g.sdo)!=null?n:!0,q=0,r,t=google.erd,v=t.jsr;google.ml=function(a,b,d,m,e){e=e===void 0?2:e;b&&(r=a&&a.message);d===void 0&&(d={});d.cad="ple_"+google.ple+".aple_"+google.aple;if(google.dl)return google.dl(a,e,d,!0),null;b=d;if(v<0){window.console&&console.error(a,b);if(v===-2)throw a;b=!1}else b=!a||!a.message||a.message==="Error loading script"||q>=l&&!m?!1:!0;if(!b)return null;q++;d=d||{};b=encodeURIComponent;var c="/gen_204?atyp=i&ei="+b(google.kEI);google.kEXPI&&(c+="&jexpid="+b(google.kEXPI));c+="&srcpg="+b(google.sn)+"&jsr="+b(t.jsr)+\n"&bver="+b(t.bv);t.dpf&&(c+="&dpf="+b(t.dpf));var f=a.lineNumber;f!==void 0&&(c+="&line="+f);var h=a.fileName;h&&(h.indexOf("-extension:/")>0&&(e=3),c+="&script="+b(h),f&&h===window.location.href&&(f=document.documentElement.outerHTML.split("\\n")[f],c+="&cad="+b(f?f.substring(0,300):"No script found.")));google.ple&&google.ple===1&&(e=2);c+="&jsel="+e;for(var u in d)c+="&",c+=b(u),c+="=",c+=b(d[u]);c=c+"&emsg="+b(a.name+": "+a.message);c=c+"&jsst="+b(a.stack||"N/A");c.length>=12288&&(c=c.substr(0,12288));a=c;m||google.log(0,"",a);return a};window.onerror=function(a,b,d,m,e){r!==a&&(a=e instanceof Error?e:Error(a),d===void 0||"lineNumber"in a||(a.lineNumber=d),b===void 0||"fileName"in a||(a.fileName=b),google.ml(a,!1,void 0,!1,a.name==="SyntaxError"||a.message.substring(0,11)==="SyntaxError"||a.message.indexOf("Script error")!==-1?3:0));r=null;p&&q>=l&&(window.onerror=null)};})();</script></head><body bgcolor="#fff"><script nonce="WArgeMBOLYhyvGzQZAykaQ">(function(){var src=\'/images/nav_logo229.png\';var iesg=false;document.body.onload = function(){window.n && window.n();if (document.images){new Image().src=src;}\nif (!iesg){document.f&&document.f.q.focus();document.gbqf&&document.gbqf.q.focus();}\n}\n})();</script><div id="mngb"><div id=gbar><nobr><b class=gb1>Pesquisa</b> <a class=gb1 href="https://www.google.com/imghp?hl=pt-BR&tab=wi">Imagens</a> <a class=gb1 href="https://maps.google.com.br/maps?hl=pt-BR&tab=wl">Maps</a> <a class=gb1 href="https://play.google.com/?hl=pt-BR&tab=w8">Play</a> <a class=gb1 href="https://www.youtube.com/?tab=w1">YouTube</a> <a class=gb1 href="https://news.google.com/?tab=wn">Not�cias</a> <a class=gb1 href="https://mail.google.com/mail/?tab=wm">Gmail</a> <a class=gb1 href="https://drive.google.com/?tab=wo">Drive</a> <a class=gb1 style="text-decoration:none" href="https://www.google.com.br/intl/pt-BR/about/products?tab=wh"><u>Mais</u> &raquo;</a></nobr></div><div id=guser width=100%><nobr><span id=gbn class=gbi></span><span id=gbf class=gbf></span><span id=gbe></span><a href="http://www.google.com.br/history/optout?hl=pt-BR" class=gb4>Hist�rico da Web</a> | <a  href="/preferences?hl=pt-BR" class=gb4>Configura��es</a> | <a target=_top id=gb_70 href="https://accounts.google.com/ServiceLogin?hl=pt-BR&passive=true&continue=https://www.google.com/&ec=GAZAAQ" class=gb4>Fazer login</a></nobr></div><div class=gbh style=left:0></div><div class=gbh style=right:0></div></div><center><br clear="all" id="lgpd"><div id="XjhHGf"><a href="/search?sca_esv=8ce15ace818c9ce3&amp;sca_upv=1&amp;ie=UTF-8&amp;q=pipoca&amp;oi=ddle&amp;ct=258248616&amp;hl=pt-BR&amp;si=ACC90nzx_D3_zUKRnpAjmO0UBLNxnt7EyN4YYdru6U3bxLI-L3LNZgm1isS2rrPBXLdJetZtLaWjnSz0NbO22zsBvqqo4QZyzR_qj2A6m8hvPc-J8QO7irw9mESuzz3yTEwAkdOKBjUBuoIZWDAsg4VnGxR32awUXw%3D%3D&amp;sa=X&amp;ved=0ahUKEwia3cD3ht-IAxWl4zgGHfs_AZ4QPQgD"><img alt="Celebrando a pipoca" border="0" height="200" src="/logos/doodles/2024/celebrating-popcorn-6753651837110076.2-l.png" title="Celebrando a pipoca" width="428" id="hplogo"><br></a><br></div><form action="/search" name="f"><table cellpadding="0" cellspacing="0"><tr valign="top"><td width="25%">&nbsp;</td><td align="center" nowrap=""><input name="ie" value="ISO-8859-1" type="hidden"><input value="pt-BR" name="hl" type="hidden"><input name="source" type="hidden" value="hp"><input name="biw" type="hidden"><input name="bih" type="hidden"><div class="ds" style="height:32px;margin:4px 0"><div style="position:relative;zoom:1"><input class="lst Ucigb" style="margin:0;padding:5px 8px 0 6px;vertical-align:top;color:#000;padding-right:38px" autocomplete="off" value="" title="Pesquisa Google" maxlength="2048" name="q" size="57"><img src="/textinputassistant/tia.png" style="position:absolute;cursor:pointer;right:5px;top:4px;z-index:300" data-script-url="/textinputassistant/13/pt-BR_tia.js" id="tsuid_1" alt="" height="23" width="27"><script nonce="WArgeMBOLYhyvGzQZAykaQ">(function(){var id=\'tsuid_1\';document.getElementById(id).onclick = function(){var s = document.createElement(\'script\');s.src = this.getAttribute(\'data-script-url\');document.body.appendChild(s);};})();</script></div></div><br style="line-height:0"><span class="ds"><span class="lsbb"><input class="lsb" value="Pesquisa Google" name="btnG" type="submit"></span></span><span class="ds"><span class="lsbb"><input class="lsb" id="tsuid_2" value="Estou com sorte" name="btnI" type="submit"><script nonce="WArgeMBOLYhyvGzQZAykaQ">(function(){var id=\'tsuid_2\';document.getElementById(id).onclick = function(){if (this.form.q.value){this.checked = 1;if (this.form.iflsig)this.form.iflsig.disabled = false;}\nelse top.location=\'/doodles/\';};})();</script><input value="AL9hbdgAAAAAZvSQvHA50-zN0vAs3HZH8TYhj-9OC9ox" name="iflsig" type="hidden"></span></span></td><td class="fl sblc" align="left" nowrap="" width="25%"><a href="/advanced_search?hl=pt-BR&amp;authuser=0">Pesquisa avan�ada</a></td></tr></table><input id="gbv" name="gbv" type="hidden" value="1"><script nonce="WArgeMBOLYhyvGzQZAykaQ">(function(){var a,b="1";if(document&&document.getElementById)if(typeof XMLHttpRequest!="undefined")b="2";else if(typeof ActiveXObject!="undefined"){var c,d,e=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"];for(c=0;d=e[c++];)try{new ActiveXObject(d),b="2"}catch(h){}}a=b;if(a=="2"&&location.search.indexOf("&gbv=2")==-1){var f=google.gbvu,g=document.getElementById("gbv");g&&(g.value=a);f&&window.setTimeout(function(){location.href=f},0)};}).call(this);</script></form><div style="font-size:83%;min-height:3.5em"><br></div><span id="footer"><div style="font-size:10pt"><div style="margin:19px auto;text-align:center" id="WqQANb"><a href="/intl/pt-BR/ads/">Publicidade</a><a href="/services/">Solu��es empresariais</a><a href="/intl/pt-BR/about.html">Sobre o Google</a><a href="https://www.google.com/setprefdomain?prefdom=BR&amp;prev=https://www.google.com.br/&amp;sig=K_wunAdrOl7eMIzM4-YSRxo4MkVm8%3D">Google.com.br</a></div></div><p style="font-size:8pt;color:#70757a">&copy; 2024 - <a href="/intl/pt-BR/policies/privacy/">Privacidade</a> - <a href="/intl/pt-BR/policies/terms/">Termos</a></p></span></center><script nonce="WArgeMBOLYhyvGzQZAykaQ">(function(){window.google.cdo={height:757,width:1440};(function(){var a=window.innerWidth,b=window.innerHeight;if(!a||!b){var c=window.document,d=c.compatMode=="CSS1Compat"?c.documentElement:c.body;a=d.clientWidth;b=d.clientHeight}\nif(a&&b&&(a!=google.cdo.width||b!=google.cdo.height)){var e=google,f=e.log,g="/client_204?&atyp=i&biw="+a+"&bih="+b+"&ei="+google.kEI,h="",k=[],l=window.google!==void 0&&window.google.kOPI!==void 0&&window.google.kOPI!==0?window.google.kOPI:null;l!=null&&k.push(["opi",l.toString()]);for(var m=0;m<k.length;m++){if(m===0||m>0)h+="&";h+=k[m][0]+"="+k[m][1]}f.call(e,"","",g+h)};}).call(this);})();</script>  <script nonce="WArgeMBOLYhyvGzQZAykaQ">(function(){google.xjs={basecomb:\'/xjs/_/js/k\\x3dxjs.hp.en.YzV18Go9T6w.es5.O/ck\\x3dxjs.hp.xiP5z-WxKJc.L.X.O/am\\x3dAQAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAQAgAAAAAAAAAAAwAoAOAAIAAAAEBAAAAgAMAAAAAAAAhiAAAFAAEAIAD8R0BgABYBACAFw/d\\x3d1/ed\\x3d1/dg\\x3d0/ujg\\x3d1/rs\\x3dACT90oG_aIpK8yasXNrfq1_LLRZCZAh7GA\',basecss:\'/xjs/_/ss/k\\x3dxjs.hp.xiP5z-WxKJc.L.X.O/am\\x3dAQAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAIACAAIAAAAEBAAAAAAAAAAAAAAAhiAAAFAAE/rs\\x3dACT90oE3p-Ya1GL1QIVYJEDFxINnM8Uhtg\',basejs:\'/xjs/_/js/k\\x3dxjs.hp.en.YzV18Go9T6w.es5.O/am\\x3dAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAwAgAMAAAAAAAAAAAAAgAMAAAAAAAAAAAAAAAAAAIAD8R0BgABYBACAFw/dg\\x3d0/rs\\x3dACT90oFZ8dPRW3vEz0HpP2bVRgolNcTNDQ\',excm:[]};})();</script>  <link href="/xjs/_/ss/k=xjs.hp.xiP5z-WxKJc.L.X.O/am=AQAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAIACAAIAAAAEBAAAAAAAAAAAAAAAhiAAAFAAE/d=1/ed=1/rs=ACT90oE3p-Ya1GL1QIVYJEDFxINnM8Uhtg/m=sb_he,d" rel="stylesheet" nonce="WArgeMBOLYhyvGzQZAykaQ">      <script nonce="WArgeMBOLYhyvGzQZAykaQ">(function(){var u=\'/xjs/_/js/k\\x3dxjs.hp.en.YzV18Go9T6w.es5.O/am\\x3dAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAwAgAMAAAAAAAAAAAAAgAMAAAAAAAAAAAAAAAAAAIAD8R0BgABYBACAFw/d\\x3d1/ed\\x3d1/dg\\x3d3/rs\\x3dACT90oFZ8dPRW3vEz0HpP2bVRgolNcTNDQ/m\\x3dsb_he,d\';var st=1;var amd=1000;var mmd=0;var pod=true;var f=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},g=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("a");},h=g(this),k=function(a,b){if(b)a:{var c=h;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in\nc))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&f(c,a,{configurable:!0,writable:!0,value:b})}};k("globalThis",function(a){return a||h});\nvar l=this||self;function m(){var a,b,c;return(a=(b=window.google)==null?void 0:(c=b.ia)==null?void 0:c.r.B2Jtyd)&&a.m===1&&a.cbfd!=null&&a.cbvi!=null?a:void 0};\nvar n=globalThis.trustedTypes,p;function q(){var a=null;if(!n)return a;try{var b=function(c){return c};a=n.createPolicy("goog#html",{createHTML:b,createScript:b,createScriptURL:b})}catch(c){}return a};var r=function(a){this.g=a};r.prototype.toString=function(){return this.g+""};function t(a){if(a instanceof r)return a.g;throw Error("b");};var w=/^\\s*(?!javascript:)(?:[\\w+.-]+:|[^:/?#]*(?:[/?#]|$))/i;var x="alternate author bookmark canonical cite help icon license modulepreload next prefetch dns-prefetch prerender preconnect preload prev search subresource".split(" ");function y(a,b){a.src=t(b);var c,d;(c=(b=(d=(c=(a.ownerDocument&&a.ownerDocument.defaultView||window).document).querySelector)==null?void 0:d.call(c,"script[nonce]"))?b.nonce||b.getAttribute("nonce")||"":"")&&a.setAttribute("nonce",c)};var z=function(a){var b=document;a=String(a);b.contentType==="application/xhtml+xml"&&(a=a.toLowerCase());return b.createElement(a)};function A(a){a=a===null?"null":a===void 0?"undefined":a;p===void 0&&(p=q());var b=p;return new r(b?b.createScriptURL(a):a)};google.ps===void 0&&(google.ps=[]);function B(){var a=u,b=function(){};google.lx=google.stvsc?b:function(){C(a);google.lx=b};google.bx||google.lx()}function D(a,b){b&&y(a,A(b));var c=a.onload;a.onload=function(d){c&&c(d);google.ps=google.ps.filter(function(e){return a!==e})};google.ps.push(a);document.body.appendChild(a)}google.as=D;function C(a){google.timers&&google.timers.load&&google.tick&&google.tick("load","xjsls");var b=z("SCRIPT");b.onerror=function(){google.ple=1};b.onload=function(){google.ple=0};google.xjsus=void 0;D(b,a);google.aple=-1;google.dp=!0}\nfunction E(){var a=[u];if(!google.dp){for(var b=0;b<a.length;b++){var c=z("LINK"),d=c,e=A(a[b]);if(e instanceof r)d.href=t(e).toString(),d.rel="preload";else{if(x.indexOf("preload")===-1)throw Error("c`preload");e=w.test(e)?e:void 0;e!==void 0&&(d.href=e,d.rel="preload")}c.setAttribute("as","script");document.body.appendChild(c)}google.dp=!0}};function F(a){var b=a.getAttribute("jscontroller");return(b==="UBXHI"||b==="R3fhkb"||b==="TSZEqd")&&a.hasAttribute("data-src")}function G(){for(var a=document.getElementsByTagName("img"),b=0,c=a.length;b<c;b++){var d=a[b];if(d.hasAttribute("data-lzy_")&&Number(d.getAttribute("data-atf"))&1&&!F(d))return!0}return!1}for(var H=document.getElementsByTagName("img"),I=0,J=H.length;I<J;++I){var K=H[I];Number(K.getAttribute("data-atf"))&1&&F(K)&&(K.src=K.getAttribute("data-src"))};var L,M,N,O,P,Q;function R(){google.xjsu=u;l._F_jsUrl=u;P=function(){B()};L=!1;M=(st===1||st===3)&&!!google.caft&&!G();N=m();O=(st===2||st===3)&&(!!google.rairicb||!!N)&&!G();Q=pod}function S(){L||M||O||(P(),L=!0)}\nsetTimeout(function(){google&&google.tick&&google.timers&&google.timers.load&&google.tick("load","xjspls");R();if(M||O){if(M){var a=function(){M=!1;S()};google.caft(a);window.setTimeout(a,amd)}O&&(a=function(){O=!1;S()},N?N.cbvi.push(a):(0,google.rairicb)(a),window.setTimeout(a,mmd));Q&&(L||E())}else P()},0);})();window._ = window._ || {};window._DumpException = _._DumpException = function(e){throw e;};window._s = window._s || {};_s._DumpException = _._DumpException;window._qs = window._qs || {};_qs._DumpException = _._DumpException;(function(){var t=[1,16,0,0,0,0,8683520,0,332608,243531826,671090720,4210688,262144,14,268435456,8712,332820,935595520,67633169,536871190,23];window._F_toggles = window._xjs_toggles = t;})();window._F_installCss = window._F_installCss || function(css){};(function(){google.jl={bfl:0,dw:false,ine:false,ubm:false,uwp:true,vs:false};})();(function(){var pmc=\'{\\x22d\\x22:{},\\x22sb_he\\x22:{\\x22agen\\x22:false,\\x22cgen\\x22:false,\\x22client\\x22:\\x22heirloom-hp\\x22,\\x22dh\\x22:true,\\x22ds\\x22:\\x22\\x22,\\x22fl\\x22:true,\\x22host\\x22:\\x22google.com\\x22,\\x22jsonp\\x22:true,\\x22msgs\\x22:{\\x22cibl\\x22:\\x22Limpar pesquisa\\x22,\\x22dym\\x22:\\x22Voc\\ê quis dizer:\\x22,\\x22lcky\\x22:\\x22Estou com sorte\\x22,\\x22lml\\x22:\\x22Saiba mais\\x22,\\x22psrc\\x22:\\x22Esta pesquisa foi removida do seu\\<a href\\x3d\\\\\\x22/history\\\\\\x22\\>Hist\\órico da web\\</a\\>\\x22,\\x22psrl\\x22:\\x22Remover\\x22,\\x22sbit\\x22:\\x22Pesquisa por imagem\\x22,\\x22srch\\x22:\\x22Pesquisa Google\\x22},\\x22ovr\\x22:{},\\x22pq\\x22:\\x22\\x22,\\x22rfs\\x22:[],\\x22stok\\x22:\\x22VwXAZXjTXgAIeWGOQF7LXI9ODY0\\x22}}\';google.pmc=JSON.parse(pmc);})();(function(){var b=function(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}};\nvar e=this||self;var g,h;a:{for(var k=["CLOSURE_FLAGS"],l=e,n=0;n<k.length;n++)if(l=l[k[n]],l==null){h=null;break a}h=l}var p=h&&h[610401301];g=p!=null?p:!1;var q,r=e.navigator;q=r?r.userAgentData||null:null;function t(a){return g?q?q.brands.some(function(c){return(c=c.brand)&&c.indexOf(a)!=-1}):!1:!1}function u(a){var c;a:{if(c=e.navigator)if(c=c.userAgent)break a;c=""}return c.indexOf(a)!=-1};function v(){return g?!!q&&q.brands.length>0:!1}function w(){return u("Safari")&&!(x()||(v()?0:u("Coast"))||(v()?0:u("Opera"))||(v()?0:u("Edge"))||(v()?t("Microsoft Edge"):u("Edg/"))||(v()?t("Opera"):u("OPR"))||u("Firefox")||u("FxiOS")||u("Silk")||u("Android"))}function x(){return v()?t("Chromium"):(u("Chrome")||u("CriOS"))&&!(v()?0:u("Edge"))||u("Silk")}function y(){return u("Android")&&!(x()||u("Firefox")||u("FxiOS")||(v()?0:u("Opera"))||u("Silk"))};var z=v()?!1:u("Trident")||u("MSIE");y();x();w();var A=!z&&!w(),D=function(a){if(/-[a-z]/.test("ved"))return null;if(A&&a.dataset){if(y()&&!("ved"in a.dataset))return null;a=a.dataset.ved;return a===void 0?null:a}return a.getAttribute("data-"+"ved".replace(/([A-Z])/g,"-$1").toLowerCase())};var E=[],F=null;function G(a){a=a.target;var c=performance.now(),f=[],H=f.concat,d=E;if(!(d instanceof Array)){var m=typeof Symbol!="undefined"&&Symbol.iterator&&d[Symbol.iterator];if(m)d=m.call(d);else if(typeof d.length=="number")d={next:b(d)};else throw Error("b`"+String(d));for(var B=[];!(m=d.next()).done;)B.push(m.value);d=B}E=H.call(f,d,[c]);if(a&&a instanceof HTMLElement)if(a===F){if(c=E.length>=4)c=(E[E.length-1]-E[E.length-4])/1E3<5;if(c){c=google.getEI(a);a.hasAttribute("data-ved")?f=a?D(a)||"":"":f=(f=\na.closest("[data-ved]"))?D(f)||"":"";f=f||"";if(a.hasAttribute("jsname"))a=a.getAttribute("jsname");else{var C;a=(C=a.closest("[jsname]"))==null?void 0:C.getAttribute("jsname")}google.log("rcm","&ei="+c+"&tgtved="+f+"&jsname="+(a||""))}}else F=a,E=[c]}window.document.addEventListener("DOMContentLoaded",function(){document.body.addEventListener("click",G)});}).call(this);</script></body></html>',
    redirect_duration: 0,
    redirect_chain_length: 0,
    http_version: "HTTP/1.1",
    tls_protocol_version: "TLS 3.4",
    browser_metrics_duration: 0,
    browser_metrics: null,
    evaluation_result: true,
  },
];

const testConfigs = [
  {
    name: "test1",
    pulse_type: "http",
    continue_on_step_failure: true,
    ssl_prove: true,
    dns_prove: true,
    mtr_prove: true,
    tags: ["tag1", "tag2"],
    url: "{{base_url}}",
    http_request_options: {
      method: "{{ method }}",
      http_version: "HTTP2FallbackToHTTP1",
      follow_redirects: true,
      timeout_seconds: 15,
      headers: [
        { name: "Content-Type", value: "application/json" },
        { name: "Accept", value: "application/json" },
      ],
      cookies: [{ name: "session_id", value: "12345" }],
    },
    query_parameters: {
      parameters: [
        { name: "param1", value: "value1" },
        { name: "param2", value: "value2" },
      ],
    },
    request_body: {
      body_type: "application/json",
      body: '{"method":"getmininginfo","params":[],"id":9056,"jsonrpc":"2.0"}',
    },
    privacy: {
      do_not_save_response_body: false,
    },
    evaluation_function:
      "ZnVuY3Rpb24gbWFpbihwYXJhbXMpIHsKICAgIGNvbnN0IG1ldHJpYyA9IHBhcmFtcz8ubWV0cmljcz8uWzBdIHx8IHt9OwogICAgY29uc3QgeyBzc2xfbWV0cmljcywgc3RhdHVzX2NvZGUsIGRuc19sb29rdXBfdGltZSB9ID0gbWV0cmljOwoKICAgIGNvbnN0IGlzU3NsVmFsaWQgPSBzc2xfbWV0cmljcz8uZGF5c191bnRpbF9leHBpcnkgPiAxMDsKICAgIGNvbnN0IGlzU3RhdHVzT2sgPSBOdW1iZXIoc3RhdHVzX2NvZGUpID09PSAyMDE7CiAgICBjb25zdCBpc0Ruc0Zhc3QgPSBkbnNfbG9va3VwX3RpbWUgPCAxOwoKICAgIHBmQWRkVmFyaWFibGUoIm5hbWUiLCAiYWxpIik7CgogICAgY29uc3Qgc3VjY2VzcyA9IGlzU3NsVmFsaWQgJiYgaXNTdGF0dXNPayAmJiBpc0Ruc0Zhc3Q7CgogICAgcmV0dXJuIHsKICAgICAgICBzdWNjZXNzOiBzdWNjZXNzLAogICAgICAgIG5hbWU6IG5hbWUKICAgIH07Cn0K",
  },
  {
    name: "test2",
    pulse_type: "http",
    continue_on_step_failure: true,
    ssl_prove: true,
    dns_prove: true,
    mtr_prove: false,
    tags: ["tag1", "tag2"],
    url: "{{base_url}}",
    http_request_options: {
      method: "{{ method }}",
      http_version: "HTTP2FallbackToHTTP1",
      follow_redirects: true,
      timeout_seconds: 15,
      headers: [
        { name: "Content-Type", value: "application/json" },
        { name: "Accept", value: "application/json" },
      ],
      cookies: [{ name: "session_id", value: "12345" }],
    },
    query_parameters: {
      parameters: [
        { name: "param1", value: "value1" },
        { name: "param2", value: "value2" },
      ],
    },
    request_body: {
      body_type: "application/json",
      body: '{"method":"getmininginfo","params":[],"id":9056,"jsonrpc":"2.0"}',
    },
    privacy: {
      do_not_save_response_body: false,
    },
    evaluation_function:
      "ZnVuY3Rpb24gbWFpbihwYXJhbXMpIHsKICB2YXIgbWF1cm8gPSAxMDsKICBsZXQgcmVzdWx0ID0gZmFsc2U7CiAgbGV0IG1lc3NhZ2UgPSAnJzsKICBsZXQgdmFyaWFibGUxID0gcGFyYW1zLnZhcmlhYmxlMSB8fCAwOwoKICAvLyBNb3JlIGNvbXBsZXggY29uZGl0aW9uYWwgbG9naWMKICBpZiAobWF1cm8gPiAxMSkgewogICAgcmVzdWx0ID0gdHJ1ZTsKICAgIG1lc3NhZ2UgPSAnTWF1cm8gaXMgZ3JlYXRlciB0aGFuIDExLic7CiAgfSBlbHNlIGlmIChtYXVybyA9PT0gMTEpIHsKICAgIHJlc3VsdCA9IGZhbHNlOwogICAgbWVzc2FnZSA9ICdNYXVybyBpcyBleGFjdGx5IDExLic7CiAgfSBlbHNlIGlmIChtYXVybyA+PSA1ICYmIG1hdXJvIDwgMTEpIHsKICAgIHJlc3VsdCA9IHRydWU7CiAgICBtZXNzYWdlID0gJ01hdXJvIGlzIGJldHdlZW4gNSBhbmQgMTAgaW5jbHVzaXZlLic7CiAgfSBlbHNlIHsKICAgIHJlc3VsdCA9IGZhbHNlOwogICAgbWVzc2FnZSA9ICdNYXVybyBpcyBsZXNzIHRoYW4gNS4nOwogIH0KCiAgLy8gQWRkaXRpb25hbCBjb25kaXRpb25hbCBmb3IgdmFyaWFibGUxCiAgaWYgKHZhcmlhYmxlMSA+IDUpIHsKICAgIG1lc3NhZ2UgKz0gJyBWYXJpYWJsZTEgaXMgZ3JlYXRlciB0aGFuIDUuJzsKICB9IGVsc2UgaWYgKHZhcmlhYmxlMSA9PT0gNSkgewogICAgbWVzc2FnZSArPSAnIFZhcmlhYmxlMSBpcyBleGFjdGx5IDUuJzsKICB9IGVsc2UgewogICAgbWVzc2FnZSArPSAnIFZhcmlhYmxlMSBpcyBsZXNzIHRoYW4gNS4nOwogIH0KCiAgcmV0dXJuIHsKICAgIHN1Y2Nlc3M6IHJlc3VsdCwKICAgIHNhYmVuZG9zOiBtYXVybywgIC8vIFJlZmVycyB0byB0aGUgdmFyaWFibGUgZGlyZWN0bHkKICAgIGZyb21fdGVzdDE6IHZhcmlhYmxlMSwKICAgIG1lc3NhZ2U6IG1lc3NhZ2UKICB9Owp9Cg==",
    // "ZnVuY3Rpb24gbWFpbihwYXJhbXMpIHsKIHZhciBtYXVybyA9IDEwCgpsZXQgcmVzdWx0ID0gZmFsc2UKaWYgKG1hdXJvID4gMTEpIHsKICAgcmVzdWx0ID0gdHJ1ZQp9CiAgcmV0dXJuIHsKICAgIHN1Y2Nlc3M6IHJlc3VsdCwKICAgIHNhYmVuZG9zOiB0aGlzLm1hdXJvLAogICAgZnJvbV90ZXN0MTogdGhpcy52YXJpYWJsZTEsCiAgfTsKfQ==",
  },
];

var requestVariables = [
  {
    method: "GET",
  },
  {
    base_url: "https://dummy-api.perfroute.com/status",
  },
  {
    name: "ali",
  },
];

module.exports = { metrics, testConfigs, requestVariables };
